cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//altadore/ray_tracer",
        "//altadore/scene_interp:scene_executer",
        "//altadore/scene_interp:scene_parser",
    ],
)
